feat: updated ani-new to use anidb

diff --git a/ani-new b/ani-new
--- a/ani-new
+++ b/ani-new
@@ -1,29 +1,35 @@
 #!/bin/sh
 
-# shellcheck disable=SC1091,SC1090
-process_response() {
-	enc_data_base64=$(printf "%s" "$1" | sed -nE 's|.*"tobeparsed":"([^"]*)".*|\1|p')
-	iv="$(printf '%s' "$enc_data_base64" | base64 -d | dd bs=1 skip=1 count=12 2>/dev/null | od -An -tx1 | tr -d ' \n')00000002"
-	[ "${#iv}" != 32 ] && error_$os "IV not present in response, maybe the episode not released..?" && exit 0
-	data="$(printf '%s' "$enc_data_base64" | base64 -d | dd bs=1 skip=13 2>/dev/null | openssl enc -d -aes-256-ctr -K "a254aa27c410f297bd04ba33a0c0df7ff4e706bf3ae27271c6703f84e750f552" -iv "$iv" -nosalt -nopad 2>/dev/null | tr '{}' '\n' | sed 's|\\u002F|\/|g;s|\\||g' | sed -nE 's|.*"sourceUrl":"([^"]*)".*"sourceName":"([^"]*)".*|\2 :\1|p')"
-}
-
-hex_decrypt() {
-	printf '%s' "$1" | sed 's/../&\n/g' | sed 's/^--$/\n/g;s/^79$/A/g;s/^7a$/B/g;s/^7b$/C/g;s/^7c$/D/g;s/^7d$/E/g;s/^7e$/F/g;s/^7f$/G/g;s/^70$/H/g;s/^71$/I/g;s/^72$/J/g;s/^73$/K/g;s/^74$/L/g;s/^75$/M/g;s/^76$/N/g;s/^77$/O/g;s/^68$/P/g;s/^69$/Q/g;s/^6a$/R/g;s/^6b$/S/g;s/^6c$/T/g;s/^6d$/U/g;s/^6e$/V/g;s/^6f$/W/g;s/^60$/X/g;s/^61$/Y/g;s/^62$/Z/g;s/^59$/a/g;s/^5a$/b/g;s/^5b$/c/g;s/^5c$/d/g;s/^5d$/e/g;s/^5e$/f/g;s/^5f$/g/g;s/^50$/h/g;s/^51$/i/g;s/^52$/j/g;s/^53$/k/g;s/^54$/l/g;s/^55$/m/g;s/^56$/n/g;s/^57$/o/g;s/^48$/p/g;s/^49$/q/g;s/^4a$/r/g;s/^4b$/s/g;s/^4c$/t/g;s/^4d$/u/g;s/^4e$/v/g;s/^4f$/w/g;s/^40$/x/g;s/^41$/y/g;s/^42$/z/g;s/^08$/0/g;s/^09$/1/g;s/^0a$/2/g;s/^0b$/3/g;s/^0c$/4/g;s/^0d$/5/g;s/^0e$/6/g;s/^0f$/7/g;s/^00$/8/g;s/^01$/9/g;s/^15$/-/g;s/^16$/./g;s/^67$/_/g;s/^46$/~/g;s/^02$/:/g;s/^17$/\//g;s/^07$/?/g;s/^1b$/#/g;s/^63$/\[/g;s/^65$/\]/g;s/^78$/@/g;s/^19$/!/g;s/^1c$/$/g;s/^1e$/&/g;s/^10$/\(/g;s/^11$/\)/g;s/^12$/*/g;s/^13$/+/g;s/^14$/,/g;s/^03$/;/g;s/^05$/=/g;s/^1d$/%/g;' | tr -d '\n'
-}
-
-domain="allanime.day"
-refer="https://youtu-chan.com"
-run_file="${TMPDIR:-/tmp}/${0##*/}_run"
+domain="https://anidb.app"
 agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/15$(head /dev/urandom | tr -dc '0-2' | cut -c1).0.0.0 Safari/537.36"
-debug=$2
+logdir="${TMPDIR:-/tmp}/${0##*/}"
 
-\cat <<EOF >"$run_file"
-search() { curl -sLXPOST -e "$refer" -H "Content-Type: application/json" "https://api.${domain}/api" -A "$agent" --data '{"variables":{"search":{"sortBy":"Recent","allowAdult":true,"allowUnknown":true,"query":"'"\$1"'"},"limit":40,"page":1,"translationType":"sub","countryOrigin":"JP"},"query":"query(\$search: SearchInput \$limit: Int \$page: Int \$translationType: VaildTranslationTypeEnumType \$countryOrigin: VaildCountryOriginEnumType) { shows( search: \$search limit: \$limit page: \$page translationType: \$translationType countryOrigin: \$countryOrigin ) {edges { _id name lastEpisodeInfo __typename}}}"}' | sed 's|Show|\n|g' | sed 's|__typename|\n|g' | sed -nE 's|.*_id":"([^"]*)","name":"([^"]*)".*sub":\{"episodeString":"([^"]*)".*|\1\t\2 Episode \3|p'; }; [ -n "\$2" ] && search "\$1"
-EOF
+get_data() {
+	curl -s "$1" -A "$agent" -e "${2:-$domain}"
+}
 
-chmod +x "$run_file"
-. "$run_file"
+search() {
+	get_data "$domain/browse?sort=order_updated&q=$1" | sed -nE 's|.*/anime/([^"]*)".*anime-card.*|\1|p'
+}
+
+download() {
+	case "$1" in
+		*m3u8*)
+			info_$os "Fetching Metadata"
+			data=$(get_data "$1" "$3" | sed '/#/d')
+			printf '%s' "$data" | nl -n'rz' | sed -E "s|^([0-9]*)[[:space:]]*(.*)|\2\n\tout=\1.ts|g" | aria2c --referer="$3" -U "$agent" -x16 -s16 -j50 -d "$logdir" -i - --download-result=hide --summary-interval=0 --allow-overwrite=true --check-certificate=false
+			info_$os "Concatenating Pieces.."
+			\cat "$logdir"/* | ffmpeg -loglevel error -stats -i - -c copy "$download_dir/$2.mp4" -y
+			[ -d "$logdir" ] && rm -rdf "$logdir"
+			;;
+		*)
+			aria2c --referer="$3" -U "$agent" --continue -x16 -s16 "$1" --dir="$download_dir" -o "$2.mp4" --download-result=hide --summary-interval=0 --allow-overwrite=true --check-certificate=false
+			;;
+	esac
+	info_$os "Downloaded $2/$4"
+}
+
+[ "$1" = "search" ] && search "$2" && exit 0
 
 case $(uname -o) in
 	*ndroid*)
@@ -33,7 +39,6 @@ case $(uname -o) in
 	*)
 		os="linux"
 		download_dir="${XDG_DOWNLOAD_DIR:-$HOME/Downloads}"
-		terminal="setsid -f ${TERMINAL:-foot} -e"
 		;;
 esac
 
@@ -45,73 +50,51 @@ info_$os "Parsing $domain.. Please wait..."
 url=$(search | (
 	case "$os" in
 		linux) menu_$os "Select Anime: " ;;
-		*) fzf --bind="change:reload:$run_file {q} 1" --prompt="Select Anime: " --with-nth 2.. -m ;;
+		*) fzf --bind="change:reload:$0 search '{q}'" --prompt="Select Anime: " ;;
 	esac
-) | tr ':' ' ' | tr -s ' ') || true
+)) || true
 
 [ -z "$url" ] && error_$os "No anime selected" && exit 0
 
-printf "%s\n" "$url" | while read -r id title; do
-	ep_no=$(printf "%s" "$title" | sed 's/.*Episode //g')
+anime_id=$(printf '%s' "$url" | sed -nE 's|.*-([0-9]*)$|\1|p')
+anime_name=$(printf '%s' "$url" | sed "s/-$anime_id//g;s/-/ /g")
+refer="$domain/anime/$url"
 
-	info_$os "Loading Episode $title.."
-	[ -n "$debug" ] && printf "\n\033[1;36m title\033[0m : %s\n" "$title"
+info_$os "Loading Episodes list: $anime_name.."
+ep=$(get_data "$domain/api/frontend/anime/$anime_id/episodes" "$refer" | sed 's/},{/\n/g' | sed -nE 's|.*"id":([0-9]*),"number":([0-9]*),.*|\2\t\1|p' | menu_$os "Select Episode: " "--with-nth=1")
 
-	#shellcheck disable=SC2016
-	process_response "$(curl -e "$refer" -sG -A "$agent" -H "Origin: $refer" "https://api.${domain}/api" --data-urlencode 'variables={"showId":"'"$id"'","translationType":"sub","episodeString":"'"$ep_no"'"}' --data-urlencode 'extensions={"persistedQuery":{"version":1,"sha256Hash":"d405d0edd690624b66baba3068e0edc3ac90f1597d898a1ec8db4e5c43c00fec"}}')"
+[ -z "$ep" ] && error_$os "No episode selected" && exit 0
 
-	[ -n "$debug" ] && printf "\n\033[1;36m Providers\033[0m : %s\n\n" "$data"
+ep_id=$(printf '%s' "$ep" | cut -f2)
+ep_number=$(printf "%s" "$ep" | cut -f1)
+title="$anime_name episode $ep_number"
 
-	info_$os "Fetching Embed links"
+info_$os "Fetching Embed link: $title"
+embed_url=$(get_data "$domain/api/frontend/episode/$ep_id/languages" "$refer" | sed -nE 's|.*"Japanese","embed_url":"(.*)"\}.*|\1|p' | sed 's/\\//g')
 
-	printf 'sharepoint\tS-mp4\nYoutube\tYt-mp4\nmp4upload\tMp4\n' | while read -r provider_name provider_regex; do
-		info_$os "Fetching $provider_name links"
-		provider_id="$(printf "%s" "$data" | sed -n "/$provider_regex :/p" | cut -d':' -f2-)"
-		[ -z "$provider_id" ] && continue
+info_$os "Extracting Episode links.."
+ep_m3u8_url=$(get_data "$embed_url" "$refer" | sed -nE "s|.*file: '([^']*)', type: 'hls'.*|\1|p")
 
-		case $provider_name in
-			mp4upload)
-				provider_video=$(curl -sLk "$provider_id" -A "$agent" -e "$refer" | sed -nE 's|.*src: "([^"]*)"[[:space:]]*|\1|p')
-				refer="$provider_id"
-				;;
-			Youtube)
-				provider_video=$(hex_decrypt "$provider_id")
-				;;
-			*)
-				provider_id="$(hex_decrypt "$provider_id" | sed "s/\/clock/\/clock\.json/")"
-				provider_video=$(curl -e "$refer" -A "$agent" -s "https://${domain}${provider_id}" | sed 's|},{|\n|g' | sed -nE 's|.*link":"([^"]*)".*"resolutionStr":"([^"]*)".*|\1|p;s|.*hls","url":"([^"]*)".*"hardsub_lang":"en-US".*|\1|p' | head -1)
-				;;
-		esac
+ep_url=$(get_data "$ep_m3u8_url" "$refer" | tee data | sed '/EXT-X-I-FRAME/,$d' | sed "s|^#.*x||g; s|,.*|p|g; /^#/d; \$!N; s|\n| >|;/^$/d" | menu_$os "Select Resolution: " | cut -d'>' -f2)
 
-		[ -z "$provider_video" ] && continue
-		[ -n "$debug" ] && printf "\033[1;32m %s\033[0m : %s\n\033[1;32m Referrer\033[0m : %s\n" "$provider_name" "$provider_video" "$refer" && continue
-		info_$os "$provider_name links fetched.."
-		choice=$(printf "stream\ndownload\ncast\nnext_mirror\nnext_anime" | menu_$os "??" '' "2")
-		[ -z "$choice" ] && break
-		case $choice in
-			stream)
-				info_$os "opening $title" "mpv"
-				# shellcheck disable=SC2086
-				player_$os "$provider_video" "$title" --referrer="$refer" --tls-verify=no
-				break
-				;;
-			cast)
-				info_$os "casting $title" "podcast"
-				catt cast "$provider_video"
-				break
-				;;
-			*mirror)
-				continue
-				;;
-			download)
-				info_$os "Downloading $title" "downloader"
-				case $provider_video in
-					*m3u*) $terminal hls -ro "$download_dir/$title" "$provider_video" || error_$os "Downloading failed $title" ;;
-					*) $terminal aria2c -U "$agent" --check-certificate=false -d "$download_dir" --summary-interval=0 -x 16 -s 16 --referer="$refer" "$provider_video" -o "$title.mp4" --download-result=hide || error_$os "Downloading failed $title" ;;
-				esac
-				info_$os "Episode Downloaded $title"
-				;;
-		esac
-		break
-	done
-done
+[ -z "$ep_url" ] && error_$os "No Resolution selected" && exit 0
+
+choice=$(printf "stream\ndownload\ncast" | menu_$os "??" '' "2")
+[ -z "$choice" ] && exit 0
+
+case $choice in
+	stream)
+		info_$os "opening $title" "mpv"
+		# shellcheck disable=SC2086
+		player_$os "$ep_url" "$title" --referrer="$refer" --tls-verify=no
+		;;
+	cast)
+		info_$os "casting $title" "podcast"
+		catt cast "$ep_url"
+		;;
+	download)
+		info_$os "Downloading $title" "downloader"
+		download "$ep_url" "$title" "$refer"
+		info_$os "Episode Downloaded $title"
+		;;
+esac
